#!/usr/bin/env node

var child_process = require('child_process'),
    fs = require('fs'),
    root = __dirname + '/../../',
    builtFile = root + 'build/glboost.js';

function setCommitVersion() {
    child_process.exec('git rev-parse HEAD', { cwd: root }, function (error, stdout, stderr) {
        var hash = stdout,
            version = hash.slice(0, 8),
            data = fs.readFileSync(builtFile, 'utf-8'),
            position = data.indexOf('// This revision is the commit right after the SHA: ') + 52, fd = fs.openSync(builtFile, 'a', 0666);

        fs.writeSync(fd, version, position);

        child_process.exec('git add ' + builtFile, { cwd: root }, function (error, stdout, stderr) {});

        console.log('Commit version set to ' + version);
    });
}

child_process.exec('npm run build', { cwd: root }, function (error, stdout, stderr) {
    if (error) {
        console.error(`exec error: ${error}`);
    
        process.exit(1);
    }

    // if git index has something changes (Modify/Delete/Add)
    child_process.exec('expr $(git status --porcelain 2>/dev/null| grep "^[M|D|A]" | wc -l)', {cwd: root}, function(error, stdout, stderr) {
        let count = stdout;

        // if this is not a empty commit,
        if (parseInt(count) > 0) {
            // Build GLBoost and insert current commit SHA to it.
            setCommitVersion();
        }
    });

});
